/**
 * Created by tegaadigu on 11/03/2018.
 */
export const CONTACT_ACTION = {
  REQUEST_CONTACTS: 'CONTACTS',
  RESPONSE_CONTACTS_SUCCESS: 'RESPONSE_CONTACTS_SUCCESS',
  RESPONSE_CONTACTS_FAIL: 'RESPONSE_CONTACTS_FAIL',

  REQUEST_CONTACT: 'CONTACT',
  RESPONSE_CONTACT_SUCCESS: 'RESPONSE_CONTACT_SUCCESS',
  RESPONSE_CONTACT_FAIL: 'RESPONSE_CONTACT_FAIL',


};